import XCTest
@testable import Clyde

final class CleatProbeTests: XCTestCase {

    /// Restore the overrides between tests so one test's mock doesn't
    /// leak into the next. The probe's overrides are `nonisolated(unsafe)`
    /// statics — fine in a single-threaded test runner but worth being
    /// strict about hygiene.
    override func tearDown() {
        CleatProbe.configPathOverride = nil
        CleatProbe.cleatOnPathOverride = nil
        super.tearDown()
    }

    // MARK: - parseConfig

    func testParseConfigReturnsEmptySetForEmptyContents() {
        XCTAssertTrue(CleatProbe.parseConfig("").isEmpty)
    }

    func testParseConfigReadsCapsSection() {
        let config = """
        [caps]
        hooks
        git
        """
        XCTAssertEqual(CleatProbe.parseConfig(config), ["hooks", "git"])
    }

    func testParseConfigIgnoresOtherSections() {
        // Defensive: cleat's current format only has `[caps]`, but
        // we shouldn't accidentally read entries from a future
        // `[settings]` block as capabilities.
        let config = """
        [settings]
        hooks_timeout = 30

        [caps]
        ssh
        """
        XCTAssertEqual(CleatProbe.parseConfig(config), ["ssh"])
    }

    func testParseConfigHandlesWhitespaceSeparatedCaps() {
        // Per cleat's TUI picker output, multiple caps on one line
        // is valid. We treat whitespace as the separator either way.
        let config = """
        [caps]
        hooks git ssh
        """
        XCTAssertEqual(CleatProbe.parseConfig(config), ["hooks", "git", "ssh"])
    }

    func testParseConfigSkipsCommentsAndBlankLines() {
        let config = """
        # User config — DO NOT EDIT by hand

        [caps]
        # everything below is generated by `cleat config`
        hooks

        """
        XCTAssertEqual(CleatProbe.parseConfig(config), ["hooks"])
    }

    // MARK: - hooksCapStatus

    func testHooksCapStatusIsNotInstalledWhenCleatNotOnPath() {
        CleatProbe.cleatOnPathOverride = false
        XCTAssertEqual(CleatProbe.hooksCapStatus(), .notInstalled)
    }

    func testHooksCapStatusIsDisabledWhenConfigMissing() {
        // A user who installed cleat but never ran `cleat config` would
        // have no config file. Default caps don't include `hooks`, so
        // we surface the advisory to nudge them to enable it.
        CleatProbe.cleatOnPathOverride = true
        CleatProbe.configPathOverride = URL(fileURLWithPath: "/tmp/clyde-test-nonexistent-\(UUID().uuidString)")
        XCTAssertEqual(CleatProbe.hooksCapStatus(), .hooksDisabled)
    }

    func testHooksCapStatusIsEnabledWhenConfigContainsHooks() {
        let url = writeTempConfig("[caps]\nhooks\n")
        CleatProbe.cleatOnPathOverride = true
        CleatProbe.configPathOverride = url
        XCTAssertEqual(CleatProbe.hooksCapStatus(), .hooksEnabled)
    }

    func testHooksCapStatusIsDisabledWhenConfigOmitsHooks() {
        let url = writeTempConfig("[caps]\ngit\nssh\n")
        CleatProbe.cleatOnPathOverride = true
        CleatProbe.configPathOverride = url
        XCTAssertEqual(CleatProbe.hooksCapStatus(), .hooksDisabled)
    }

    // MARK: - helpers

    private func writeTempConfig(_ contents: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("clyde-cleat-config-\(UUID().uuidString)")
        try? contents.write(to: url, atomically: true, encoding: .utf8)
        return url
    }
}
